---
version: "3"

tasks:

  force-update:
    desc: Force rebuild on all containers
    cmds:
      - |
        find . -name metadata.json | while read -r metadata; do
            __app=$(echo "${metadata}" | awk -F / '{print $3}')
            __current_version=$(jq --raw-output ".__current_version" "${metadata}")
            __stream=$(echo "${metadata}" | awk -F / '{print $4}')
            __latest_version="$(bash "$(dirname "$(dirname "${metadata}")")"/latest-version.sh "${__stream}")"
            if [[ -n "${__latest_version}" || "${__latest_version}" != "null" ]]; then
                jq --arg v "$(date --rfc-3339=seconds --utc)" '.__build_status.__ts = $v' "${metadata}" | sponge "${metadata}"
                echo "${__app} | ${__stream} | ${__current_version} | ${__latest_version} | ${metadata}"
            fi
        done
