---
version: "3"

includes:
  base:
    taskfile: .taskfiles/BuildTasks.yml
    vars:
      BASE: true
  app:
    taskfile: .taskfiles/BuildTasks.yml
    vars:
      BASE: false

tasks:
  default:
    silent: true
    cmds:
      - task -l
