name: Check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Install OS tools
        run: |
          sudo apt install moreutils jo
      - name: Fetch new app versions
        run: |
          find . -name metadata.json | while read metadata; do
              __app=$(echo "${metadata}" | awk -F / '{print $3}')
              __current_version=$(jq --raw-output ".__current_version" "${metadata}")
              __stream=$(echo "${metadata}" | awk -F / '{print $4}')
              __latest_version="$(bash $(dirname $(dirname "${metadata}"))/latest-version.sh "${__stream}")"
              if [[ -n "${__latest_version}" || "${__latest_version}" != "null" ]]; then
                  jq --arg v "$__latest_version" '.__current_version = $v' "${metadata}" | sponge "${metadata}"
                  jq '.__build_status.__success = true' "${metadata}" | sponge "${metadata}"
                  echo "${__app} | ${__stream} | ${__current_version} | ${__latest_version} | ${metadata}"
              fi
          done
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "ci: add new release versions"
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          pull: "--rebase --autostash"
          add: "*.json"
