---
name: Fetch

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
  push:
    paths:
      - '.github/scripts/fetch.sh'
      - '.github/workflows/fetch.yaml'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
          fetch-depth: 1
      - name: Install OS tools
        run: |
          sudo apt-get install moreutils jo
      - name: Fetch new app versions
        id: fetch
        run: ./.github/scripts/fetch.sh
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: |-
            ${{ steps.fetch.outputs.commit-message }}
          default_author: github_actions
          pull: "--rebase --autostash"
          add: "*.json --force"
