---
name: Fetch

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"
  push:
    paths:
      - '.github/scripts/fetch.sh'
      - '.github/workflows/fetch.yaml'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
          fetch-depth: 1

      - name: Install OS tools
        run: |
          sudo apt-get install moreutils jo

      - name: Fetch new app versions
        id: fetch
        run: ./.github/scripts/fetch.sh

      - name: Git pull in changes
        run: git pull --rebase --autostash

      - name: Git commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: |-
            ${{ steps.fetch.outputs.commit-message }}
          file_pattern: "images/*.json"
          push_options: "--force"
