---
name: Fetch Test

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 */4 * * *"
  push:
    paths:
      - '.github/scripts/*.sh'
      - '.github/workflows/fetch_test.yaml'
      - '.github/workflows/release_test.yaml'

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  fetch:
    name: Fetch Test
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.fetch.outputs.changes }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ env.TOKEN }}

      - name: Install tools
        run: |
          sudo apt-get install moreutils jo

      - name: Fetch new app versions
        id: fetch
        run: ./.github/scripts/fetch_test.sh

  dispatch:
    name: Dispatch Test
    runs-on: ubuntu-latest
    needs:
      - fetch
    strategy:
      matrix: ${{ fromJson(needs.fetch.outputs.matrix) }}
      fail-fast: false
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ env.TOKEN }}
          repository: onedr0p/containers
          event-type: release-dispatcher
          client-payload: ${{ toJson(matrix.changes) }}
