---
name: "Get Changed Images"

on:
  workflow_call:
    outputs:
      addedOrModified:
        description: "Whether any files were added or modified"
        value: ${{ jobs.get-changed-images.outputs.addedOrModified }}
      addedOrModifiedImages:
        description: "The images that were added or modified"
        value: ${{ jobs.get-changed-images.outputs.addedOrModifiedImages }}
    secrets:
      BOT_APP_ID:
        description: "The ID of the GitHub App"
        required: true
      BOT_APP_PRIVATE_KEY:
        description: "The private key of the GitHub App"
        required: true

jobs:
  get-changed-images:
    name: Get Changed Images
    runs-on: ubuntu-latest
    outputs:
      addedOrModified: "${{ steps.filter.outputs.addedOrModified }}"
      addedOrModifiedImages: "${{ steps.filter-containers.outputs.addedOrModifiedImages }}"
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@e995b4e40ace2eb5bf13137d9abe242c98f3aab6 # v1.6.0
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Collect changed files
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
        id: filter
        with:
          list-files: json
          filters: |
            addedOrModified:
              - added|modified: 'apps/*/**'

      - name: Determine changed images
        if: ${{ steps.filter.outputs.addedOrModified == 'true' }}
        id: filter-containers
        shell: bash
        run: |
          PATHS='${{ steps.filter.outputs.addedOrModified_files }}'
          OUTPUT=$(echo $PATHS | jq --raw-output -c 'map(. |= split("/")[1]) | unique | join(",")')
          echo "addedOrModifiedImages=${OUTPUT}" >> $GITHUB_OUTPUT
