name: "Images build"

on:
  workflow_call:
    inputs:
      imagesToBuild:
        required: false
        type: string
        default: ''
      pushImages:
        required: false
        default: 'false'
        type: string

jobs:
  generate-build-matrix:
    name: Generate matrix for building images
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-changed.outputs.changes }}
    if: inputs.imagesToBuild != ''
    steps:
      - name: Install tools
        run: sudo apt-get install moreutils jo

      - name: Fetch modified images
        id: get-changed
        shell: bash
        run: |
          IFS=' ' read -a images <<< "${{ inputs.imagesToBuild }}"
          output="$(jo changes="$(jo -a "${images[@]}")")"
          echo "::set-output name=changes::${output}"

  debug:
    name: Debug
    runs-on: ubuntu-latest
    needs:
      - generate-build-matrix
    if: inputs.imagesToBuild != ''
    strategy:
      matrix: ${{ fromJson(needs.generate-build-matrix.outputs.matrix) }}
      fail-fast: false
    steps:
      - name: Debug
        run: |
          echo "${{ toJson(matrix.changes) }}"
