---
name: Manual Release

on:
  workflow_dispatch:
    inputs:
      app:
        description: "App (e.g. radarr)"
        default: ""
        required: true
      channels:
        description: "Channels (e.g. master,develop)"
        default: ""
        required: true
      push:
        description: "Push"
        default: "false"
        required: false

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Install tools
        run: sudo apt-get install moreutils jo
      
      - name: Build payload
        id: payload
        run: |-
          app=${{ github.event.inputs.app }}
          channels=${{ github.event.inputs.channels }}
          push=${{ github.event.inputs.push }}
          payload=$(jo app=${app} push=${{ github.event.inputs.push }} channels=$(jo -a ${channels/,/ }))
          echo "::set-output name=data::${payload}"

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ env.TOKEN }}
          repository: onedr0p/containers
          event-type: release-dispatch
          client-payload: ${{ steps.payload.outputs.data }}
