---
name: Release

on:
  repository_dispatch:
    types: [release]

env:
  # renovate: datasource=github-releases depName=aelsabbahy/goss
  GOSS_VERSION: v0.3.18

jobs:
  changes:
    name: Get changes
    runs-on: ubuntu-latest
    outputs:
      app: ${{ steps.filter.outputs.app }}
      channels: ${{ steps.filter.outputs.channels }}
    steps:
      - uses: actions/checkout@v3
      - name: Test
        id: filter
        run: |-
          app=$(jq --raw-output '.app | [.]' <<< '${{ toJson(github.event.client_payload.changes) }}')
          echo "${app}"
          channels=$(jq --raw-output '.channels' <<< '${{ toJson(github.event.client_payload.changes) }}')
          echo "${channels}"
          echo ::set-output name=app::${app}
          echo ::set-output name=channels::${channels}
  
  build:
    name: Build Test
    runs-on: ubuntu-latest
    needs:
      - changes
    strategy:
      matrix: 
        app: ${{ fromJson(needs.changes.outputs.app) }}
        channel: ${{ fromJson(needs.changes.outputs.channels) }}
      fail-fast: false
    steps:
      - name: Test
        id: envs
        run: |-
          echo "${{ matrix.app }}"
          echo "${{ matrix.channel }}"
