---
name: Release Test

on:
  repository_dispatch:
    types: [release]

jobs:
  setup:
    name: Setup Matrix Test
    runs-on: ubuntu-latest
    outputs:
      app: ${{ steps.filter.outputs.app }}
      channels: ${{ steps.filter.outputs.channels }}
    steps:
      - uses: actions/checkout@v3
      - name: Test
        id: filter
        run: |-
          app=$(jq --raw-output '.app | [.]' <<< '${{ toJson(github.event.client_payload.changes) }}')
          echo "${app}"
          channels=$(jq --raw-output '.channels' <<< '${{ toJson(github.event.client_payload.changes) }}')
          echo "${channels}"
          echo ::set-output name=app::${app}
          echo ::set-output name=channels::${channels}
  
  build:
    name: Build Container Test
    runs-on: ubuntu-latest
    needs:
      - setup
    strategy:
      matrix: 
        app: ${{ fromJson(needs.setup.outputs.app) }}
        channel: ${{ fromJson(needs.setup.outputs.channels) }}
      fail-fast: false
    steps:
      - name: Test
        id: envs
        run: |-
          echo "${{ matrix.app }}"
          echo "${{ matrix.channel }}"
