---
name: Release Schedule

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 */4 * * *"
  push:
    paths:
      - '.github/scripts/*.sh'
      - '.github/workflows/fetch.yaml'
      - '.github/workflows/release.yaml'

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.fetch.outputs.changes }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ env.TOKEN }}

      - name: Fetch new app versions
        id: fetch
        run: ./.github/scripts/fetch.sh

  dispatch:
    name: Dispatch
    runs-on: ubuntu-latest
    needs:
      - setup
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
      fail-fast: false
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ env.TOKEN }}
          repository: onedr0p/containers
          event-type: release-dispatch
          client-payload: ${{ toJson(matrix.changes) }}
